# Generated by Django 5.2.8 on 2025-11-27 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('manage_team', 'Can manage users and team settings')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
