# Generated by Django 5.2.8 on 2025-11-27 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'permissions': [('manage_inventory', 'Can manage inventory records')]},
        ),
    ]
